### ISSUE TITLE
Dark Theme does not extend to Admin Panel pages

### ISSUE THREAD

**Issue by ghost** [Adaoh2/bitwardenvault-dark#2]
The different pages in the Admin Panel currently look like this:

![img](https://xbb.datahoarder.dev/VUSu3/xUHOSUya20.gif/raw)

**Comment by mxmvncnt** [comment]
Hello, I do not have Bitwarden_rs, so i cannot really make the dark mode for it. However, if you give me the url of the portal (for example for the bitwarden hosted client, it is vault.bitwarden.com), I can maybe try to exclude the admin portal so that it is at least readable even if not dark. Tho i cannot really find a way to easily exclude a site, ill try to do my best.

**Comment by whalehub** [comment]
@Adaoh2 If you'd like, I could host a demo instance of Bitwarden_rs for you where you have access to the admin page. If you're on Discord, I can send you the credentials there.

Stylus has a menu toggle for excluding the current URL, so working around this issue on the client side is simple enough for now.

![img](https://xbb.datahoarder.dev/VUSu3/rODajAtA44.gif/raw)
